### ISSUE TITLE
second-stage model outputs almost identical values for different samples

### ISSUE THREAD

**Issue by chenyugoal** [Milan-BUAA/TSAN-brain-age-estimation#11]
Dear authors,

I observed the same behavior described in #10 . The second-stage model outputs almost identical values for different samples if the predicted ages by the first-stage model fall into the same discretization interval. Do you have an explanation of the possible causes of this behavior? @JianCheng @liuziyang1106 

Thank you!

**Comment by liuziyang1106** [comment]
Thank you for your interest in our project. You can contact me via email （liuziyang1106@buaa.edu.cn）to provide more details, and I will try to help you solve this problem.
