### ISSUE TITLE
pip -r install requirements.txt?

### ISSUE THREAD

**Issue by qqman481** [Milan-BUAA/TSAN-brain-age-estimation#2]
The installed environment does not match the code
pytorch==1.7.0?
python==3.8.5?

**Comment by ZhyCong** [comment]
I also encountered this problem, how can this problem be solved?

**Comment by ZhyCong** [comment]
> The installed environment does not match the code
> pytorch==1.7.0?
> python==3.8.5?

I also encountered this problem, how can this problem be solved?
