### ISSUE TITLE
Pretrained model download issue

### ISSUE THREAD

**Issue by gaborleko** [Milan-BUAA/TSAN-brain-age-estimation#4]
Dear Owner!
I have the following issue: everytime, when I try to download the pretrained models, the download process always reaches a point where it cannot go any further and the download process failes. I tried with different browsers, computers, and networks, but the issue is always present. Could you check please if the models are still downloadable? Thank you in advance!
Regards,
Gabor Leko

**Comment by liuziyang1106** [comment]
I have just tested it on my machine and it can be downloaded normally. You can try again later.

**Comment by liuziyang1106** [comment]
> Dear Owner!
> I have the following issue: everytime, when I try to download the pretrained models, the download process always reaches a point where it cannot go any further and the download process failes. I tried with different browsers, computers, and networks, but the issue is always present. Could you check please if the models are still downloadable? Thank you in advance!
> Regards,
> Gabor Leko

I have just tested it on my machine and it can be downloaded normally. You can try again later.
