### ISSUE TITLE
The PAC 2019 cannot be downloaded

### ISSUE THREAD

**Issue by Super-1123** [Milan-BUAA/TSAN-brain-age-estimation#5]
Dear all,

How to obtain the raw nifiti format dataset of PAC 2019 ? I found no place to download it from the website link. Could anyone give me a kind help?

**Comment by JianCheng** [comment]
Hi, 

We obtained the PAC 2019 data from the PAC 2019 competition. However, we found the competition and download links are invalid in 2021. You could find PAC information from https://web.archive.org/web/20200214101600/https://www.photon-ai.com/pac2019. We have the data, but we cannot send it to you without the permission of the PAC organizers. Maybe you could ask the PAC organizer for the data.
Anyway, you could test the algorithm in any public data, or private data you have. 

Thanks for your interests.
