### ISSUE TITLE
Could you please share the specific IDs of healthy subjects of ADNI-1 during the classification task?

### ISSUE THREAD

**Issue by Super-1123** [Milan-BUAA/TSAN-brain-age-estimation#6]
Hi,
I'm deeply interested with this model and want to reproduce the classification results using the pretrained model. However, I don;t know the IDs of the  40 healthy subjects of ADNI-1 in the classification task. Could you kindly share the subject IDs with me ? Many thanks!

**Comment by Super-1123** [comment]
By the way, I tested the model on my own data recently, however I got an error as "local variable 'img' referenced before assignment". How to fix it?

**Comment by liuziyang1106** [comment]
Hi, 
For your first question, maybe you can leave your email or contact me directly be email, and we will send you the ADNI-1 IDs in our work.

And for the next question, in our code, you need to make sure that the image data in the folder corresponds to the data in the Excel Table. If there is an image data's ID doesn't exist in the Excel table, you will get the error "local iamge referenced before assignment".

**Comment by liuziyang1106** [comment]
By the way, thanks for your interesting so much.

**Comment by Super-1123** [comment]
> Hi, For your first question, maybe you can leave your email or contact me directly be email, and we will send you the ADNI-1 IDs in our work.
> 
> And for the next question, in our code, you need to make sure that the image data in the folder corresponds to the data in the Excel Table. If there is an image data's ID doesn't exist in the Excel table, you will get the error "local iamge referenced before assignment".

Thanks for your kind reply! My e-mail address is: 583509006@qq.com. Thanks a lot!
