### ISSUE TITLE
getting error while trying to open the link of pretrained model

### ISSUE THREAD

**Issue by itamoh1907** [Milan-BUAA/TSAN-brain-age-estimation#7]
HI there. Thanks for sharing your code. I just wanted to apply pretrained model to the other dataset, but the link doesn't work properly. I would really appreciate if you could share the pretrained model.
If you don't mind I share my email address: zardosht.m@gmail.com

**Comment by nguizard** [comment]
Same issue for me. Thanks

**Comment by liuziyang1106** [comment]
Thank you for your attention. In fact, I just tested it, and I was able to download the pretrained model by the released link. I will update the download link or add a link to another cloud drive.
